[build]
  functions = "netlify/functions"

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "http://strengthoverspeed.net/*"
  to = "https://strengthoverspeed.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.strengthoverspeed.net/*"
  to = "https://strengthoverspeed.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.strengthoverspeed.net/*"
  to = "https://strengthoverspeed.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/events"
  to = "/meetings.html"
  status = 301

[[redirects]]
  from = "/events/*"
  to = "/meetings.html"
  status = 301
